// File generated by flutterfire configure.
// This is a template file. You need to run 'flutterfire configure' to generate
// the actual configuration with your Firebase project details.
//
// To generate this file properly:
// 1. Install flutterfire_cli: dart pub global activate flutterfire_cli
// 2. Run: flutterfire configure
// 3. Select your Firebase project and platforms

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtnB-4YPqD_rSVWumrFaXvqGu94oUgigc',
    appId: '1:553789382722:web:25f55a8a61cfd191798ddb',
    messagingSenderId: '553789382722',
    projectId: 'varim-app-a390d',
    authDomain: 'varim-app-a390d.firebaseapp.com',
    storageBucket: 'varim-app-a390d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: 'YOUR_ANDROID_APP_ID',
    messagingSenderId: '553789382722',
    projectId: 'varim-app-a390d',
    storageBucket: 'varim-app-a390d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: '553789382722',
    projectId: 'varim-app-a390d',
    storageBucket: 'varim-app-a390d.firebasestorage.app',
    iosBundleId: 'com.example.varimApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: '553789382722',
    projectId: 'varim-app-a390d',
    storageBucket: 'varim-app-a390d.firebasestorage.app',
    iosBundleId: 'com.example.varimApp',
  );
}
