import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:provider/provider.dart';
import 'package:varim_app/theme/app_theme.dart';
import 'package:varim_app/screens/main_screen.dart';
import 'package:varim_app/screens/login_screen.dart';
import 'package:varim_app/providers/user_provider.dart';

// Import firebase_options.dart - this file is generated by running: flutterfire configure
// If you see an error here, run: dart pub global activate flutterfire_cli && flutterfire configure
import 'firebase_options.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Firebase
  try {
    // Check if Firebase is already initialized
    if (Firebase.apps.isEmpty) {
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
      debugPrint('Firebase initialized successfully');
    } else {
      debugPrint('Firebase already initialized');
    }
  } catch (e, stackTrace) {
    // If Firebase initialization fails, log the error with stack trace
    debugPrint('Firebase initialization error: $e');
    debugPrint('Stack trace: $stackTrace');
    debugPrint('Please run: dart pub global activate flutterfire_cli');
    debugPrint('Then run: flutterfire configure');
    debugPrint('Or update firebase_options.dart with your Firebase project details');
    // Continue running the app - AuthGate will handle the error state
  }
  
  runApp(const VarimApp());
}

class VarimApp extends StatelessWidget {
  const VarimApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => UserProvider()),
      ],
      child: MaterialApp(
        title: 'VARIM',
        debugShowCheckedModeBanner: false,
        theme: AppTheme.darkTheme,
        home: const AuthGate(),
      ),
    );
  }
}

/// Gatekeeper widget that routes based on authentication state
/// Uses StreamBuilder to listen to FirebaseAuth authStateChanges()
class AuthGate extends StatelessWidget {
  const AuthGate({super.key});

  @override
  Widget build(BuildContext context) {
    // Check if Firebase is initialized
    try {
      if (Firebase.apps.isEmpty) {
        // Firebase not initialized - show error screen
        return const _FirebaseErrorScreen();
      }

      return StreamBuilder<User?>(
        stream: FirebaseAuth.instance.authStateChanges(),
        builder: (context, snapshot) {
          // While waiting for auth state check, show loading screen
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const _LoadingScreen();
          }

          // If user is logged in (hasData and data is not null) -> MainScreen
          if (snapshot.hasData && snapshot.data != null) {
            return const MainScreen();
          }

          // If user is logged out (data is null) -> LoginScreen
          return const LoginScreen();
        },
      );
    } catch (e) {
      // If there's an error accessing Firebase, show error screen
      debugPrint('AuthGate error: $e');
      return const _FirebaseErrorScreen();
    }
  }
}

/// Loading screen shown while checking authentication state
class _LoadingScreen extends StatelessWidget {
  const _LoadingScreen();

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final varimColors = AppTheme.varimColors(context);

    return Scaffold(
      backgroundColor: theme.colorScheme.surface,
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Container(
              padding: const EdgeInsets.all(20),
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  begin: Alignment.topLeft,
                  end: Alignment.bottomRight,
                  colors: [
                    varimColors.headerAccent,
                    varimColors.headerAccent.withValues(alpha: 0.6),
                  ],
                ),
                borderRadius: BorderRadius.circular(20),
                boxShadow: [
                  BoxShadow(
                    color: varimColors.headerAccent.withValues(alpha: 0.4),
                    blurRadius: 20,
                    spreadRadius: 2,
                  ),
                ],
              ),
              child: Text(
                'VARIM',
                style: theme.textTheme.displayLarge?.copyWith(
                      fontWeight: FontWeight.w900,
                      color: theme.colorScheme.onSurface,
                      letterSpacing: 4,
                    ),
              ),
            ),
            const SizedBox(height: 32),
            CircularProgressIndicator(
              valueColor: AlwaysStoppedAnimation<Color>(
                varimColors.varimColor,
              ),
            ),
          ],
        ),
      ),
    );
  }
}

/// Error screen shown when Firebase is not properly configured
class _FirebaseErrorScreen extends StatelessWidget {
  const _FirebaseErrorScreen();

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final varimColors = AppTheme.varimColors(context);

    return Scaffold(
      backgroundColor: theme.colorScheme.surface,
      body: SafeArea(
        child: Center(
          child: Padding(
            padding: const EdgeInsets.all(24),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Icon(
                  Icons.error_outline,
                  size: 64,
                  color: varimColors.yokumColor,
                ),
                const SizedBox(height: 24),
                Text(
                  'Firebase Yapılandırma Hatası',
                  style: theme.textTheme.headlineSmall?.copyWith(
                        fontWeight: FontWeight.w800,
                        color: varimColors.yokumColor,
                      ),
                  textAlign: TextAlign.center,
                ),
                const SizedBox(height: 16),
                Text(
                  'Firebase düzgün yapılandırılmamış. Lütfen firebase_options.dart dosyasını Firebase proje bilgilerinizle güncelleyin.',
                  style: theme.textTheme.bodyMedium,
                  textAlign: TextAlign.center,
                ),
                const SizedBox(height: 32),
                Container(
                  padding: const EdgeInsets.all(16),
                  decoration: BoxDecoration(
                    color: theme.colorScheme.surfaceContainer,
                    borderRadius: BorderRadius.circular(12),
                    border: Border.all(
                      color: varimColors.yokumColor.withValues(alpha: 0.3),
                    ),
                  ),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'Çözüm:',
                        style: theme.textTheme.titleSmall?.copyWith(
                              fontWeight: FontWeight.w700,
                            ),
                      ),
                      const SizedBox(height: 8),
                      Text(
                        '1. Firebase Console\'da bir proje oluşturun\n'
                        '2. Terminal\'de şu komutu çalıştırın:\n'
                        '   flutterfire configure\n'
                        '3. Veya firebase_options.dart dosyasını manuel olarak güncelleyin',
                        style: theme.textTheme.bodySmall,
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
